### ISSUE TITLE
fix zero state

### ISSUE THREAD

**Issue by yujing-student** [yujing-student/component-building-block#33]
<h1>de groene border moet niet zichtbaar zijn</h1>

![image](https://github.com/user-attachments/assets/a6fbc47b-e268-4373-b63e-b0fd13ad8add)

de groene border moet pas zichtbaar zijn nadat er iets ingevuld is
![image](https://github.com/user-attachments/assets/d32e6ef0-e8aa-4fbf-b389-d7e68434a9e1)

**Comment by yujing-student** [comment]
![image](https://github.com/user-attachments/assets/906963b5-d73d-4c1a-a131-c41fc2d0c916)

Met deze code word er pas user state gegeven nadat de gebruiker wat invuld

```css

    input[type='text']:user-valid,
    input[type='email']:valid,
    input[type='number']:valid,
    textarea:valid,
    select:user-valid {
        outline: 2px solid green;

    }


    input[type='text']:user-invalid,
    input[type='email']:user-invalid,
    input[type='number']:user-invalid,
    textarea:user-invalid,
    select:user-invalid {
        outline: 2px solid red;
    }
```

<hr>
hier kan je zien dat er een false state is en een successtate

![image](https://github.com/user-attachments/assets/d6a5db60-3ff7-41c8-9adf-28dc1487d80e)

ook word er aangegeven welke velden verplicht zijn

![image](https://github.com/user-attachments/assets/34945999-6260-423b-98f2-05d9c6102957)
