### ISSUE TITLE
opnieuw stylen button 

### ISSUE THREAD

**Issue by yujing-student** [yujing-student/component-building-block#35]
<h1>opnieuw stylen button met het design</h1>

na het mergen met de main is er wat missgegaan omdat in de global.css er border-box-sizing stond en dit had ik niet in mijn component

![image](https://github.com/user-attachments/assets/bd008b13-cf18-4f00-b2a3-36cc0589af2d)

**Comment by yujing-student** [comment]
dit heb ik aangepast

![image](https://github.com/user-attachments/assets/0476a245-6041-4b5b-9166-03cafb51f91d)

```css
.button{
        border-left: 1px solid var(--grey);
        border-right: 1px solid var(--grey);
        border-top: 1px solid var(--grey);
        border-bottom: 1px solid var(--grey);
        margin-right: -0.3rem;
        color: var(--black);
        text-decoration: none;
        padding: 0px 0.2rem 0.4rem 0.4rem;
        background-color: transparent;

    }
    .button:hover{
        color: var(--blue);
    }

    button:focus {
        outline: 2px solid var(--blue);
    }

```
