### ISSUE TITLE
de astrix groter maken of zelf een ster icoon maken met css 

### ISSUE THREAD

**Issue by yujing-student** [yujing-student/component-building-block#37]
![image](https://github.com/user-attachments/assets/dd15b484-7d4c-4740-88bd-6c6958ee8c5f)

met css before en after astrix maken en dit ook meer zichtbaar bij elkaar neerzetten

**Comment by yujing-student** [comment]
![image](https://github.com/user-attachments/assets/cd9793f4-23c9-4bf8-b02f-a4dda001e007)

**Comment by yujing-student** [comment]
Ik heb een span toevoegd met de class star en die bent ik gaan stylen waardoor het beter zichtbaar is dat je dit veld verplicht moet invullen

```html
      <span class="star">Functie</span>

```


```css
    .star:after{
        content: "*";
        font-size: 2rem;
        color: red;

    }
```
