### ISSUE TITLE
fixen verplichte velden textarea dat je erst wat invult en daarna pas de state ziet

### ISSUE THREAD

**Issue by yujing-student** [yujing-student/component-building-block#38]
als je niks invult is het al groen

![image](https://github.com/user-attachments/assets/35b22208-382a-4572-b699-f884548e1e04)

**Comment by yujing-student** [comment]
<h1>dit heb ik opgelost</h1>

de empty state is deze
![image](https://github.com/user-attachments/assets/f690263f-9c3e-4009-8876-283c641cd6ab)

als je niks invult en op submit drukt dan krijg je de failed state en word die rood
![image](https://github.com/user-attachments/assets/2d8922e2-cc91-4ec3-8366-ab8d253bcc15)


vul je wat in dan word het groen en komt de successtate

![image](https://github.com/user-attachments/assets/170a22f7-a740-4292-bae1-22f71914d89b)


```css

    input[type='text']:user-valid,
    input[type='email']:valid,
    input[type='number']:valid,
    textarea:valid,
    select:user-valid {
        outline: 2px solid green;

    }

    /* form focus invalid */

    input[type='text']:user-invalid,
    input[type='email']:user-invalid,
    input[type='number']:user-invalid,
    textarea:user-invalid,
    select:user-invalid {
        outline: 2px solid red;
    }
```
